server:
  port: 8070

spring:
  application:
    name: eureka
  config:
    import: "optional:configserver:http://configserver:8071"
  cloud:
    config:
      fail-fast: false

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always