example.property=I AM PROD
spring.datasource.url=jdbc:postgresql://localhost:5432/cloudprod
spring.datasource.username=postgres
spring.datasource.password={chiper}bc52809f0035fe4bc22aa74a65bbeeac473c3461dd921c29198cb8b5236c2b24