example.property=I AM DEV
# DataSource settings: set here your own configurations for the database
spring.datasource.url=jdbc:postgresql://database:5432/cloud_dev
spring.datasource.username=user
spring.datasource.password=postgres