base.property=I AM THE DEFAULT
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://eureka:8070/eureka/
# --- CircuitBreaker ---
resilience4j.circuitbreaker.instances.license.sliding-window-size=20
resilience4j.circuitbreaker.instances.license.minimum-number-of-calls=10
resilience4j.circuitbreaker.instances.license.failure-rate-threshold=60
resilience4j.circuitbreaker.instances.license.wait-duration-in-open-state=15s
resilience4j.circuitbreaker.instances.license.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.license.record-exceptions=org.springframework.web.client.HttpServerErrorException,java.io.IOException,java.util.concurrent.TimeoutException,org.springframework.web.client.ResourceAccessException
# --- Retry ---
resilience4j.retry.instances.retryLicense.max-attempts=5
resilience4j.retry.instances.retryLicense.wait-duration=2s
resilience4j.retry.instances.retryLicense.enable-exponential-backoff=true
resilience4j.retry.instances.retryLicense.exponential-backoff-multiplier=2
resilience4j.retry.instances.retryLicense.retry-exceptions=java.util.concurrent.TimeoutException
# --- Bulkhead ---
resilience4j.bulkhead.instances.bulkheadLicense.max-concurrent-calls=20
resilience4j.bulkhead.instances.bulkheadLicense.max-wait-duration=500ms
# --- RateLimiter ---
resilience4j.ratelimiter.instances.license.limit-for-period=100
resilience4j.ratelimiter.instances.license.limit-refresh-period=1s
resilience4j.ratelimiter.instances.license.timeout-duration=2s
