# DataSource settings: set here your own configurations for the database
spring.datasource.url = jdbc:postgresql://database:5432/cloudev
spring.datasource.username = postgres
spring.datasource.password = {chiper}bc52809f0035fe4bc22aa74a65bbeeac473c3461dd921c29198cb8b5236c2b24