spring:
  application:
    name: organization
  cloud:
    config:
      enabled: true
      profile: dev
      uri: http://localhost:8071
  config:
    import: "optional:configserver:http://localhost:8071,
    optional:configserver:http://host.docker.internal:8071,
    optional:configserver:http://configserver:8071"
