management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://jaeger:4318/v1/traces

server:
  port: 8080

spring:
  application:
    name: organization
  cloud:
    config:
      enabled: true
      uri: http://configserver:8071
  config:
    import: "optional:configserver:http://configserver:8071"
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.organization: DEBUG
    liquibase: WARN
    org.hibernate.SQL: WARN